version: "3"
services:
  postgres:
    image: postgres:12
    container_name: images_postgres
    restart: always
    environment:
      POSTGRES_USER: vas3k
      POSTGRES_PASSWORD: vas3k
      POSTGRES_DB: vas3k_images
    volumes:
      - /home/vas3k/pgdata:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:5432:5432"
